### ISSUE TITLE
Another way to run Rust functions in Tencent Serverless.

### ISSUE THREAD

**Issue by alabulei1** [johnmave126/tencent_scf#4]
Hi John,

Sorry to bother you. I came across your GitHub repo in Rustcc.cn. What you are doing is similar to us. We are running the Rust functions in Tencent Serverless through SSVM(WebAssembly VM) to run the TensorFlow model. You can check out this GitHub repo: https://github.com/second-state/tencent-tensorflow-scf

If you don't mind, I would like to add you as a WeChat friend. My WeChat ID is h0923xw. Thanks! Hope to have more connections with you!

**Comment by johnmave126** [comment]
Added
